name: 'Chromatic'

on:
  pull_request:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: yarn
        run: yarn

      - name: build
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowConsoleErrors: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
